// pages/login.vue
<template>
  <div>
    <Head>
      <Title>Ecolabz</Title>
      <Meta name="description" content="Ecolabz site" />
    </Head>
    <NavigationBar/>
    <div class="container-lg ">
      <!-- Form -->
      <div class="login-page">
        <div v-if="authenticateUser.loginError">
        <div class="text-center h3 text-danger">
          Unauthorized user
        </div></div>
        <div v-else class="row align-items-center justify-content-around">
          <div class="col-12 col-lg-6 col-sm-6">
            <div class="text-center h3">Welcome Back!</div>
            <div class="text-center h4 pb-4">Login in by entering the information below</div>
            <form @submit.prevent="submitForm">
              <label for="email">Email</label>

              <div class="form-group">
                <input
                  type="email"
                  class="form-control-input mt-2"
                  placeholder="Email"
                  required
                 v-model="_email"
                />
              </div>

              <label for="from">Password</label>

              <div class="form-group">
                <input
                  type="password"
                  class="form-control-input mt-2"
                  placeholder="password"
                  required
                  v-model="_password"
                />
              </div>

              <div class="form-group text-center">
                <button type="submit" class="form-control-submit-button">
                  login
                </button>
              </div>
            </form>
            <!-- end of form -->
          </div>
        </div>
      </div>
    </div>
    <Footer/>
  </div>
</template>

<script setup>
import { getQuotes } from '~/store'


const authenticateUser = getQuotes();

const _email = ref("");
const _password = ref("");



const submitForm = () => {
  let data = {
    email: _email.value,
    password: _password.value
}

    authenticateUser.LOGIN(data);
}


</script>

// src/pages/Login.tsx
import { getAuth, signInWithEmailAndPassword } from "firebase/auth";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const Login = () => {
  const [userData, setUserData] = useState({
    email: "",
    password: "",
  });

  const [loginError, setLoginError] = useState("");

  const navigate = useNavigate();

  const handleChange = (e: any) => {
    const _name = e.currentTarget.name;
    const _value = e.currentTarget.value;

    setUserData((prev) => {
      return { ...prev, [_name]: _value };
    });
  };

  const signIn = (e: any) => {
    e.preventDefault();

    signInWithEmailAndPassword(getAuth(), userData.email, userData.password)
      .then((cred: any) => {
        setUserData(cred.user.email);
        toast("Successfully logged in!");
        window.localStorage.setItem("currentUser", `${cred.user.email}`);
        navigate("/quote");
      })
      .catch(() => {
        setLoginError("An error occured, please check credentials");
      });
  };

  return (
    <>
      <div className="container-lg ">
        <div className="login-page">
          <div className="row align-items-center justify-content-around">
            <div className="col-12 col-lg-6 col-sm-6">
              <div className="text-center h3">Welcome Back!</div>
              <div className="text-center h4 pb-4">
                Login in by entering the information below
              </div>
              {!loginError ? (
                ""
              ) : (
                <div style={{ color: "#FF0000", marginBottom: "1rem" }}>
                  {loginError}
                </div>
              )}
              <form onSubmit={signIn}>
                <label htmlFor="email">Email</label>

                <div className="form-group">
                  <input
                    type="email"
                    className="form-control-input mt-2"
                    placeholder="Email"
                    required
                    name="email"
                    onChange={handleChange}
                  />
                </div>

                <label htmlFor="from">Password</label>

                <div className="form-group">
                  <input
                    type="password"
                    className="form-control-input mt-2"
                    placeholder="password"
                    required
                    name="password"
                    onChange={handleChange}
                  />
                </div>

                <div className="form-group text-center">
                  <button type="submit" className="form-control-submit-button">
                    login
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Login;
