// pages/register.vue
<template>
  <div>
    <Head>
      <Title>Ecolabz</Title>
      <Meta name="description" content="Ecolabz site" />
    </Head>
    <div class="container-lg mt-5">
      <!-- Form -->
      <div class="">
        <div class="row align-items-center justify-content-around">
          <div class="col-12 col-lg-6 col-sm-6">
            <div class="text-center h2 pb-3">Register</div>
            <form @submit.prevent="submitForm">
              <!-- <label for="display_name">Display Name</label>

              <div class="form-group">
                <input
                  type="text"
                  class="form-control-input mt-2"
                  placeholder="Display Name"
                  required
                 v-model="_display_name"
                />
              </div> -->
              <label for="email">Email</label>

              <div class="form-group">
                <input
                  type="email"
                  class="form-control-input mt-2"
                  placeholder="Email"
                  required
                  v-model="_email"
                />
              </div>

              <label for="from">Password</label>

              <div class="form-group">
                <input
                  type="password"
                  class="form-control-input mt-2"
                  placeholder="password"
                  required
                  v-model="_password"
                />
              </div>

              <div class="form-group text-center">
                <button type="submit" class="form-control-submit-button">
                  Register
                </button>
              </div>
            </form>
            <!-- end of form -->
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { getQuotes } from "~/store";

const authenticateUser = getQuotes();

const _email = ref("");
const _password = ref("");

const submitForm = () => {
  let data = {
    email: _email.value,
    password: _password.value,
    // displayName: _display_name.value
  };

  authenticateUser.REGISTER(data);
};
</script>

// src/pages/Register.tsx
import { getAuth, createUserWithEmailAndPassword } from "firebase/auth";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const Register = () => {
  const [userData, setUserData] = useState({
    email: "",
    password: "",
  });
  const navigate = useNavigate();

  const handleChange = (e: any) => {
    const _name = e.currentTarget.name;
    const _value = e.currentTarget.value;

    setUserData((prev) => {
      return { ...prev, [_name]: _value };
    });
  };

  const registerUser = (e: any) => {
    e.preventDefault();

    try {
      createUserWithEmailAndPassword(
        getAuth(),
        userData.email,
        userData.password
      ).then((cred: any) => {
        setUserData(cred.user.email);
        toast("Successfully registered!");
        window.localStorage.setItem("currentUser", `${cred.user.email}`);
        navigate("/quote");
      });
    } catch (error: any) {
      throw Error(error.Message);
    }
  };

  return (
    <>
      <div className="container-lg ">
        <div className="login-page">
          <div className="row align-items-center justify-content-around">
            <div className="col-12 col-lg-6 col-sm-6">
              {/* <div className="text-center h3">Register!</div> */}
              <div className="text-center h4 pb-4">
                Register by entering the information below
              </div>
              <form onSubmit={registerUser}>
                <label htmlFor="email">Email</label>

                <div className="form-group">
                  <input
                    type="email"
                    className="form-control-input mt-2"
                    placeholder="Email"
                    required
                    name="email"
                    onChange={handleChange}
                  />
                </div>

                <label htmlFor="from">Password</label>

                <div className="form-group">
                  <input
                    type="password"
                    className="form-control-input mt-2"
                    placeholder="password"
                    required
                    name="password"
                    onChange={handleChange}
                  />
                </div>

                <div className="form-group text-center">
                  <button type="submit" className="form-control-submit-button">
                    Register
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Register;
