// pages/quote/index.vue
<template>
  <div>
    <Head>
      <Title>Ecolabz</Title>
      <Meta name="description" content="Ecolabz site" />
    </Head>

    <section class="card-table">
      <!-- start of container-lg -->
      <div class="custom-container pt-1 pb-3">
        <div class="row align-items-center justify-content-sm-between pt-4">
          <div class="col-sm-8 col-12">
            <div class="h2">Admin Dashboard</div>
            <p class="fw-normal">
              Quotes from potenial clients. Please delete items after you have
              contacted the client to free up space
            </p>
          </div>
          <div class="col-sm-4 col-12 text-end">
            <div class="btn btn-outline-danger" @click="logout">Logout</div>
          </div>
        </div>
      </div>
      <!-- end of row -->

      <div class="header-container">
        <div class="text-lead">Qoute Service</div>
        <div class="row">
          <div class="col-1">
            <div class="header">Company</div>
          </div>
          <div class="col-2">
            <div class="header">Name</div>
          </div>
          <div class="col-3">
            <div class="header">Email</div>
          </div>
          <div class="col-4">
            <div class="header">Service</div>
          </div>
          <div class="col-5">
            <div class="header">Budget</div>
          </div>
        </div>
      </div>
      <div v-if="computeQuote.loadingQuotes">
        <div class="text-center mt-5">
          <section class="loading">
            <div class="loader">
              <!-- <span style="--i: 1"></span>
            <span style="--i: 2"></span>
            <span style="--i: 3"></span>
            <span style="--i: 4"></span>
            <span style="--i: 5"></span> -->
              <span style="--i: 6"></span>
              <span style="--i: 7"></span>
              <span style="--i: 8"></span>
              <span style="--i: 9"></span>
              <span style="--i: 10"></span>
              <span style="--i: 11"></span>
              <span style="--i: 12"></span>
              <span style="--i: 13"></span>
              <span style="--i: 14"></span>
              <span style="--i: 15"></span>
              <span style="--i: 16"></span>
              <span style="--i: 17"></span>
              <span style="--i: 18"></span>
              <span style="--i: 19"></span>
              <span style="--i: 20"></span>
            </div>
          </section>
        </div>
      </div>
      <div v-else>
        <div v-for="q in computeQuote.quotes" :key="q.id" class="sub-container">
          <NuxtLink :to="{ name: 'quote-slug', params: { slug: q.id } }">
            <div class="row">
              <div class="col-1">
                <div class="sub-text">
                  {{ q.company_name.length == "" ? "N/A" : q.company_name }}
                </div>
              </div>
              <div class="col-2">
                <div class="sub-text">
                  {{ q.name.length == "" ? "N/A" : q.name }}
                </div>
              </div>
              <div class="col-3">
                <div class="sub-text">
                  {{ q.email.length == "" ? "N/A" : q.email }}
                </div>
              </div>
              <div class="col-4">
                <div class="sub-text loop-items">
                  <div v-for="s in q.services" :key="s.id" class="items">
                    {{ s }}
                  </div>
                </div>
              </div>
              <div class="col-5">
                <div class="sub-text loop-items">
                  <div class="budget">
                    {{ q.budget.length == "" ? "N/A" : q.budget }}
                  </div>
                </div>
              </div>
            </div>
          </NuxtLink>
          <!-- <a :href="`/quote/${q.id}`" class="category-style">
            <div class="row">
              <div class="col-1">
                <div class="sub-text">{{ q.company_name }}</div>
              </div>
              <div class="col-2">
                <div class="sub-text">{{ q.name }}</div>
              </div>
              <div class="col-3">
                <div class="sub-text">{{ q.email }}</div>
              </div>
              <div class="col-4">
                <div class="sub-text loop-items">
                  <div v-for="s in q.services" :key="s.id" class="items">
                    {{ s }}
                  </div>
                </div>
              </div>
              <div class="col-5">
                <div class="sub-text loop-items">
                  <div v-for="b in q.budget" :key="b.id" class="budget">
                    {{ b }}
                  </div>
                </div>
              </div>
            </div>
          </a> -->
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { getQuotes } from "~/store";

definePageMeta({
  middleware: [
    async function () {
      const authenticateUser = getQuotes();
      if (!authenticateUser.user) {
        return navigateTo("/login");
      }
    },
  ],
});

const computeQuote = getQuotes();
computeQuote.GET_QUOTES();

const logout = () => {
  computeQuote.LOGOUT();
};
</script>

<style>
</style>

// src/pages/quote/Quote.tsx
import { useState, useEffect } from "react";
import { Link, Navigate } from "react-router-dom";
import { getAuth, signOut } from "firebase/auth";
import { getDocs } from "firebase/firestore";
import { ToastContainer } from "react-toastify";
import { toast } from "react-toastify";

import { q } from "../../App";

const Quote = () => {
  const [quotes, setQuotes] = useState<any>([]);

  useEffect(() => {
    const getPost = async () => {
      const postSnapshot = await getDocs(q);
      const postList = postSnapshot.docs.map((doc) => ({
        ...doc.data(),
        id: doc.id,
      }));
      // Set the result to the useState.
      setQuotes(postList);
    };
    // Call the async function.
    getPost().catch(console.error);
  }, []);

  if (!window.localStorage.getItem("currentUser")) {
    return <Navigate to="/" replace={true} />;
  }

  return (
    <>
      <section className="card-table">
        <ToastContainer />
        <div className="custom-container pt-1 pb-3">
          <div className="row align-items-center justify-content-sm-between pt-4">
            <div className="col-sm-8 col-12">
              <div className="h2">Admin Dashboard</div>
              <p className="fw-normal">
                Quotes from potenial clients. Please delete items after you have
                contacted the client to free up space
              </p>
            </div>
            <div className="col-sm-4 col-12 text-end">
              <div
                className="btn btn-outline-danger"
                onClick={() =>
                  signOut(getAuth())
                    .then(() => {
                      toast("Successfully logged out!");
                      window.localStorage.removeItem("currentUser");
                      window.location.href = "/";
                    })
                    .catch((err) => {
                      console.log(err.message);
                    })
                }
              >
                Logout
              </div>
            </div>
          </div>
        </div>

        <div className="header-container">
          <div className="text-lead">Qoute Service</div>
          <div className="row">
            <div className="col-1">
              <div className="header">Name</div>
            </div>
            <div className="col-2">
              <div className="header">Phone no</div>
            </div>
            <div className="col-3">
              <div className="header">Email</div>
            </div>
            <div className="col-4">
              <div className="header">Service</div>
            </div>
            <div className="col-5">
              <div className="header">Message</div>
            </div>
          </div>
        </div>
        {quotes.length === 0 ? (
          <div className="text-center mt-3 lead">Not data available</div>
        ) : (
          quotes.map((data: any) => (
            <div className="sub-container" key={data.id}>
              <Link to={`/quote/${data.id}`}>
                <div className="row">
                  <div className="col-1">
                    <div className="sub-text">
                      {data.name} {data.length}
                    </div>
                  </div>
                  <div className="col-2">
                    <div className="sub-text">
                      {!data.phone_no ? "N/A" : data.phone_no}
                    </div>
                  </div>
                  <div className="col-3">
                    <div className="sub-text">{data.email}</div>
                  </div>
                  <div className="col-4">
                    <div className="sub-text loop-items">
                      {data.services.map((item: any, index: number) => (
                        <div className="items" key={index}>
                          {item.name}
                        </div>
                      ))}
                    </div>
                  </div>
                  <div className="col-5">
                    <div className="sub-text">
                      {!data.message
                        ? "Message not availabe"
                        : data.message.substring(0, 40)}{" "}
                      {data.message.length >= 20 && "..."}
                    </div>
                  </div>
                </div>
              </Link>
            </div>
          ))
        )}
      </section>
    </>
  );
};

export default Quote;
